kind: Deployment
apiVersion: apps/v1
metadata:
  name: fights-messaging
  namespace: superheroes
  labels:
    app: fights-messaging
    app.kubernetes.io/component: messagebroker
    app.kubernetes.io/part-of: fights-service
    app.openshift.io/runtime: amq
    application: fights-service
    logging: elasticsearch
    system: quarkus-super-heroes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fights-messaging
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: fights-service
        name: fights-messaging
        system: quarkus-super-heroes
    spec:
      containers:
        - resources:
            limits:
              memory: 768Mi
            requests:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          name: fights-messaging
          command:
            - sh
            - '-c'
            - 'export CLUSTER_ID=$(bin/messaging-storage.sh random-uuid) && bin/messaging-storage.sh format -t ${CLUSTER_ID} -c config/kraft/server.properties && bin/messaging-server-start.sh config/kraft/server.properties --override advertised.listeners=${messaging_ADVERTISED_LISTENERS}'
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: messaging_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://fights-messaging:9092'
            - name: messaging_HEAP_OPTS
              value: '-Xmx128M -Xms128M'
          ports:
            - containerPort: 9092
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'quay.io/strimzi/messaging:0.43.0-messaging-3.8.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600