apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: sre-assistant
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: sre-assistant
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--max-model-len'
        - '4096'
        #- '--dtype=half' # add this if working with older GPUs e.g. Tesla T4
        # '--tensor_parallel_size' # add this and next line if consuming multiple GPUs within one worker node
        #- '2' 
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '10'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '6'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: sre-assistant
      storageUri: 'oci://quay.io/mmurakam/model-cars:sre-assistant-v0.1.0'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists